#!/bin/sh

# This script is run when creating your first Xenial zfs root image, after
# running mkzpool to create the pool and some of the datasets - all except for
# home, ubuntu, and swap.  mkubuntu creates a minimal bootable ROOT/ubuntu
# dataset and installs grub.  

set -e

DESTPOOL=$1
if ! zpool list $DESTPOOL >/dev/null 2>&1; then
	zpool import -N -R /mnt $DESTPOOL >/dev/null 2>&1 || true
	if ! zpool list $DESTPOOL >/dev/null 2>&1; then
		echo "pool $DESTPOOL does not exist" 1>&2
		exit 1
	fi
fi

DESTROOTFS=$DESTPOOL/ROOT/ubuntu
SNAP_DEBOOTSTRAP=$DESTROOTFS@install-debootstrap
SNAP_KERNEL=$DESTROOTFS@install-kernel

if ! zfs list $SNAP_DEBOOTSTRAP >/dev/null 2>&1; then
	# MOUNT
	zfs create -o canmount=noauto -o mountpoint=/ $DESTROOTFS
	zfs mount $DESTROOTFS
	zfs mount -a # TODO this could have unintended consequences in a non-livecd context
	test -d /mnt/var/tmp || mkdir /mnt/var/tmp
	chmod 1777 /mnt/var/tmp

	# BOOTSTRAP
	apt-get install --yes debootstrap
	debootstrap xenial /mnt
	zfs set devices=off $DESTPOOL
	zfs snapshot $SNAP_DEBOOTSTRAP
fi

if ! zfs list $SNAP_KERNEL >/dev/null 2>&1; then
	umount /mnt/proc || true
	mount -t proc proc /mnt/proc
	umount /mnt/sys || true
	mount -t sysfs sysfs /mnt/sys
	umount /mnt/dev || true
	mount -t devtmpfs udev /mnt/dev

	# MISC
	echo root:temprootpw | chroot /mnt chpasswd
	chroot /mnt locale-gen en_US.UTF-8
	echo 'LANG="en_US.UTF-8"' > /mnt/etc/default/locale
	chroot /mnt addgroup --system lpadmin
	chroot /mnt addgroup --system sambashare

	ln -fs /proc/self/mounts /mnt/etc/mtab

	# KERNEL
	cat - > /mnt/etc/apt/sources.list <<EOF
deb http://archive.ubuntu.com/ubuntu xenial main universe
deb-src http://archive.ubuntu.com/ubuntu xenial main universe
deb http://security.ubuntu.com/ubuntu xenial-security main universe
deb-src http://security.ubuntu.com/ubuntu xenial-security main universe
deb http://archive.ubuntu.com/ubuntu xenial-updates main universe
deb-src http://archive.ubuntu.com/ubuntu xenial-updates main universe
EOF
	chroot /mnt apt-get update
	chroot /mnt apt-get install --yes ubuntu-minimal openssh-server etckeeper
	chroot /mnt apt-get install --yes --no-install-recommends linux-image-generic

	echo /dev/zvol/$DESTPOOL/swap none swap defaults 0 0 > /mnt/etc/fstab
	chroot /mnt etckeeper commit "add swap to fstab"

	#chroot /mnt dpkg-reconfigure tzdata
	#chroot /mnt etckeeper commit "set timezone"

	zfs snapshot $SNAP_KERNEL

	# TODO execute these on exit trap too
	umount /mnt/proc
	umount /mnt/sys
	umount /mnt/dev
fi
