#!/bin/sh

poolname=$1

set -e

cd /dev/disk/by-id
for i in *; do 
  if [ `readlink $i` = "../../sdb" ]; then
    disk=/dev/disk/by-id/$i
    #echo 'Acquire::http::Proxy "http://192.168.2.171:3142";' > /etc/apt/apt.conf.d/01proxy
    /home/vagrant/mkzpool $poolname $disk
    /home/vagrant/mkubuntu $poolname $disk
    /home/vagrant/mkgrub $poolname $disk
    exit 0
  fi
done
exit 1
